Repository microsoft/azure_arc, pull requests merged in 2024-11, with the labels that each got.

#2794 Remove pindown for WinGet modules
  azure_jumpstart_arcbox/artifacts/WinGet.ps1
  azure_jumpstart_hcibox/artifacts/PowerShell/WinGet.ps1
Labels: ArcBox, HCIBox

#2804 Agora 2.0 - Fabric automation updates
  azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1
  azure_jumpstart_ag/artifacts/PowerShell/SetupFabricWorkspace.ps1
  azure_jumpstart_ag/artifacts/fabric/Contoso-Hypermarket.zip
  azure_jumpstart_ag/contoso_hypermarket/bicep/data/dataflows.bicep
  azure_jumpstart_ag/contoso_hypermarket/bicep/data/script.kql
Labels: review

#2805 Add Hypermarket GItOps Config
  azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-hypermarket.psd1
  azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1
Labels: needs author feedback, review

#2823 Agora 2.0 - updated login method for tests
  azure_jumpstart_ag/artifacts/PowerShell/tests/common.tests.ps1
  azure_jumpstart_ag/artifacts/PowerShell/tests/k8s.tests.ps1
Labels: Agora

#2837 Agora 2.0 - test optimizations
  azure_jumpstart_ag/artifacts/PowerShell/tests/k8s.tests.ps1
Labels: Agora

#2756 VBumps for Oct ArcData Release
  arc_data_services/charts/arcdataservices/values.yaml
  arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
  arc_data_services/deploy/yaml/bootstrapper-unified.yaml
  arc_data_services/deploy/yaml/bootstrapper.yaml
  arc_data_services/deploy/yaml/data-controller.yaml
  arc_data_services/deploy/yaml/uninstall.yaml
  arc_data_services/test/launcher/base/kustomization.yaml
  arc_data_services/upgrade/yaml/bootstrapper-upgrade-job.yaml
  arc_data_services/upgrade/yaml/data-controller-upgrade.yaml
  arc_data_services/upgrade/yaml/request_body/request-body-after.yaml
  arc_data_services/upgrade/yaml/request_body/request-body-before.yaml
  azure_arc_data_jumpstart/aks/ARM/artifacts/DataServicesLogonScript.ps1
  azure_arc_data_jumpstart/aks/DR/ARM/artifacts/DataServicesLogonScript.ps1
  azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
  azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1
  azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
  azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/DataServicesLogonScript.ps1
  azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1
  azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
Labels: needs author feedback, no recent activity

#2867 Windows Server 2025 support in ArcBox
  azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
  azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
  azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
  azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
  azure_jumpstart_arcbox/artifacts/WinGet.ps1
  azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_itpro.dsc.yml
  azure_jumpstart_arcbox/artifacts/installK3s.sh
  azure_jumpstart_arcbox/artifacts/tests/Invoke-Test.ps1
  azure_jumpstart_arcbox/artifacts/tests/itpro.tests.ps1
  azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
Labels: ArcBox
